import prisma from '@/lib/db';
import { MenuItemWithDetails } from '@/lib/types';

/**
 * THE BROAST FACTORY - Official Menu & Dish Photography
 * Transcribed directly from the official printed in-store menu card.
 */

export const OFFICIAL_CATEGORIES = [
  {
    id: 'cat-broasted-chicken',
    name: 'Broasted Chicken',
    slug: 'broasted-chicken',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-broasted-fish',
    name: 'Broasted Fish',
    slug: 'broasted-fish',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-burgers',
    name: 'Burgers',
    slug: 'burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-wraps',
    name: 'Wraps',
    slug: 'wraps',
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-boneless',
    name: 'Boneless',
    slug: 'boneless',
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-loaded',
    name: 'Loaded Chicken',
    slug: 'loaded-chicken',
    imageUrl: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-fries',
    name: 'Fries',
    slug: 'fries',
    imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-salads',
    name: 'Salads',
    slug: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-addons',
    name: 'Add-Ons',
    slug: 'add-ons',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
  },
];

export const OFFICIAL_MENU_ITEMS: MenuItemWithDetails[] = [
  // 1. BROASTED CHICKEN
  {
    id: 'item-broast-10',
    name: 'Broast Chicken (10 Pcs)',
    slug: 'broast-chicken-10-pcs',
    description: '10 Pieces of golden pressure-fried crispy broasted chicken. Served with 4 Buns, 3 Garlic Dips, and hot Fries.',
    price: 750,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: '/images/dishes/broast-chicken-10-pcs.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 25,
    sortOrder: 1,
    optionGroups: [
      {
        id: 'og-broast-10-spice',
        name: 'Spice Level',
        menuItemId: 'item-broast-10',
        isRequired: true,
        minSelections: 1,
        maxSelections: 1,
        options: [
          { id: 'opt-b10-orig', name: 'Original Crispy', price: 0, optionGroupId: 'og-broast-10-spice', isAvailable: true },
          { id: 'opt-b10-spicy', name: 'Spicy Masala', price: 0, optionGroupId: 'og-broast-10-spice', isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-broast-2',
    name: 'Broast Chicken (2 Pcs)',
    slug: 'broast-chicken-2-pcs',
    description: '2 Succulent pieces of golden crispy broasted chicken. Served with 1 Bun and 1 Garlic Dip.',
    price: 200,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: '/images/dishes/broast-chicken-2-pcs.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 15,
    sortOrder: 2,
    optionGroups: [
      {
        id: 'og-broast-2-spice',
        name: 'Spice Level',
        menuItemId: 'item-broast-2',
        isRequired: true,
        minSelections: 1,
        maxSelections: 1,
        options: [
          { id: 'opt-b2-orig', name: 'Original Crispy', price: 0, optionGroupId: 'og-broast-2-spice', isAvailable: true },
          { id: 'opt-b2-spicy', name: 'Spicy Masala', price: 0, optionGroupId: 'og-broast-2-spice', isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-broast-5',
    name: 'Broast Chicken (5 Pcs)',
    slug: 'broast-chicken-5-pcs',
    description: '5 Pieces of crispy golden broasted chicken. Served with 2 Buns, 1 Garlic Dip, and hot Fries.',
    price: 400,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 20,
    sortOrder: 3,
    optionGroups: [
      {
        id: 'og-broast-5-spice',
        name: 'Spice Level',
        menuItemId: 'item-broast-5',
        isRequired: true,
        minSelections: 1,
        maxSelections: 1,
        options: [
          { id: 'opt-b5-orig', name: 'Original Crispy', price: 0, optionGroupId: 'og-broast-5-spice', isAvailable: true },
          { id: 'opt-b5-spicy', name: 'Spicy Masala', price: 0, optionGroupId: 'og-broast-5-spice', isAvailable: true },
        ],
      },
    ],
  },
  {
    id: 'item-leg-5',
    name: 'Leg Pieces (5 Pcs)',
    slug: 'leg-pieces-5-pcs',
    description: '5 Crispy seasoned chicken drumsticks fried to golden perfection. Served with 2 Buns, 1 Garlic Dip, and hot Fries.',
    price: 450,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1585325701165-351af916e581?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 18,
    sortOrder: 4,
    optionGroups: [],
  },
  {
    id: 'item-leg-10',
    name: 'Leg Pieces (10 Pcs)',
    slug: 'leg-pieces-10-pcs',
    description: '10 Juicy and crispy seasoned chicken drumsticks. Served with 4 Buns, 3 Garlic Dips, and hot Fries.',
    price: 900,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 25,
    sortOrder: 5,
    optionGroups: [],
  },
  {
    id: 'item-wings-4',
    name: 'Chicken Wings (4 Pcs)',
    slug: 'chicken-wings-4-pcs',
    description: '4 Crunchy, deep-fried chicken wings served with 1 Garlic Dip.',
    price: 250,
    categoryId: 'cat-broasted-chicken',
    category: { id: 'cat-broasted-chicken', name: 'Broasted Chicken', slug: 'broasted-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 15,
    sortOrder: 6,
    optionGroups: [],
  },

  // 2. BROASTED FISH
  {
    id: 'item-fish-10',
    name: 'Fish Fillets (10 Pcs)',
    slug: 'fish-fillets-10-pcs',
    description: '10 Pieces of tender fish fillets coated in seasoned batter and fried crispy. Served with 3 Buns and 3 Garlic Dips.',
    price: 599,
    categoryId: 'cat-broasted-fish',
    category: { id: 'cat-broasted-fish', name: 'Broasted Fish', slug: 'broasted-fish' },
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 20,
    sortOrder: 7,
    optionGroups: [],
  },
  {
    id: 'item-fish-5',
    name: 'Fish Fillets (5 Pcs)',
    slug: 'fish-fillets-5-pcs',
    description: '5 Pieces of golden fried fish fillets. Served with 2 Buns and 1 Garlic Dip.',
    price: 300,
    categoryId: 'cat-broasted-fish',
    category: { id: 'cat-broasted-fish', name: 'Broasted Fish', slug: 'broasted-fish' },
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 15,
    sortOrder: 8,
    optionGroups: [],
  },

  // 3. FRIES
  {
    id: 'item-salted-fries',
    name: 'Salted Fries',
    slug: 'salted-fries',
    description: 'Classic salted golden potato French fries fried fresh and crispy.',
    price: 100,
    categoryId: 'cat-fries',
    category: { id: 'cat-fries', name: 'Fries', slug: 'fries' },
    imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 8,
    sortOrder: 9,
    optionGroups: [],
  },
  {
    id: 'item-piri-piri-fries',
    name: 'Piri Piri Fries',
    slug: 'piri-piri-fries',
    description: 'Crispy French fries generously dusted with spicy and tangy peri-peri seasoning.',
    price: 120,
    categoryId: 'cat-fries',
    category: { id: 'cat-fries', name: 'Fries', slug: 'fries' },
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 8,
    sortOrder: 10,
    optionGroups: [],
  },

  // 4. SALADS
  {
    id: 'item-chicken-salad',
    name: 'Chicken Salad',
    slug: 'chicken-salad',
    description: 'Fresh crisp greens tossed with tender shredded chicken and creamy house dressing.',
    price: 120,
    categoryId: 'cat-salads',
    category: { id: 'cat-salads', name: 'Salads', slug: 'salads' },
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 10,
    sortOrder: 11,
    optionGroups: [],
  },
  {
    id: 'item-veg-salad',
    name: 'Vegetable Salad',
    slug: 'vegetable-salad',
    description: 'Fresh crunchy cucumber, garden lettuce, ripe tomatoes, and dressing.',
    price: 100,
    categoryId: 'cat-salads',
    category: { id: 'cat-salads', name: 'Salads', slug: 'salads' },
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 8,
    sortOrder: 12,
    optionGroups: [],
  },

  // 5. WRAPS (Includes Mayonnaise Dip + Cool Drink)
  {
    id: 'item-crispy-wrap',
    name: 'Chicken Crispy Wrap',
    slug: 'chicken-crispy-wrap',
    description: 'Crispy fried tenders wrapped in a warm tortilla with iceberg lettuce and garlic cream. Includes Mayonnaise Dip + Cool Drink.',
    price: 150,
    categoryId: 'cat-wraps',
    category: { id: 'cat-wraps', name: 'Wraps', slug: 'wraps' },
    imageUrl: '/images/dishes/chicken-crispy-wrap.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 12,
    sortOrder: 13,
    optionGroups: [],
  },
  {
    id: 'item-nugget-wrap',
    name: 'Chicken Nugget Wrap',
    slug: 'chicken-nugget-wrap',
    description: 'Crispy chicken nuggets wrapped with fresh vegetables and creamy mayo. Includes Mayonnaise Dip + Cool Drink.',
    price: 150,
    categoryId: 'cat-wraps',
    category: { id: 'cat-wraps', name: 'Wraps', slug: 'wraps' },
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 12,
    sortOrder: 14,
    optionGroups: [],
  },
  {
    id: 'item-fish-wrap',
    name: 'Fish Wrap',
    slug: 'fish-wrap',
    description: 'Crispy golden fish fillet wrapped in soft flatbread with zesty tartar mayo. Includes Mayonnaise Dip + Cool Drink.',
    price: 140,
    categoryId: 'cat-wraps',
    category: { id: 'cat-wraps', name: 'Wraps', slug: 'wraps' },
    imageUrl: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 12,
    sortOrder: 15,
    optionGroups: [],
  },

  // 6. BURGERS (Includes Mayonnaise Dip + Cool Drink)
  {
    id: 'item-crispy-burger',
    name: 'Crispy Burger',
    slug: 'crispy-burger',
    description: 'Hand-breaded crispy fried chicken fillet, crunchy lettuce, and house sauce on toasted brioche bun. Includes Mayonnaise Dip + Cool Drink.',
    price: 150,
    categoryId: 'cat-burgers',
    category: { id: 'cat-burgers', name: 'Burgers', slug: 'burgers' },
    imageUrl: '/images/dishes/crispy-burger.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 15,
    sortOrder: 16,
    optionGroups: [],
  },
  {
    id: 'item-nugget-burger',
    name: 'Nugget Burger',
    slug: 'nugget-burger',
    description: 'Layered crispy chicken nuggets inside a soft sesame bun with creamy mayonnaise. Includes Mayonnaise Dip + Cool Drink.',
    price: 150,
    categoryId: 'cat-burgers',
    category: { id: 'cat-burgers', name: 'Burgers', slug: 'burgers' },
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 12,
    sortOrder: 17,
    optionGroups: [],
  },
  {
    id: 'item-fish-burger',
    name: 'Fish Burger',
    slug: 'fish-burger',
    description: 'Crispy breaded fish fillet topped with fresh lettuce and tartar mayonnaise on a soft toasted bun. Includes Mayonnaise Dip + Cool Drink.',
    price: 140,
    categoryId: 'cat-burgers',
    category: { id: 'cat-burgers', name: 'Burgers', slug: 'burgers' },
    imageUrl: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 12,
    sortOrder: 18,
    optionGroups: [],
  },

  // 7. BONELESS (Includes Mayonnaise Dip)
  {
    id: 'item-chicken-nuggets',
    name: 'Chicken Nuggets',
    slug: 'chicken-nuggets',
    description: '10 Pieces of bite-sized golden chicken nuggets fried crispy. Served with Mayonnaise Dip.',
    price: 170,
    categoryId: 'cat-boneless',
    category: { id: 'cat-boneless', name: 'Boneless', slug: 'boneless' },
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 10,
    sortOrder: 19,
    optionGroups: [],
  },
  {
    id: 'item-chicken-strips',
    name: 'Chicken Strips',
    slug: 'chicken-strips',
    description: '5 Pieces of 100% whole breast chicken tender strips, golden crusted and juicy. Served with Mayonnaise Dip.',
    price: 170,
    categoryId: 'cat-boneless',
    category: { id: 'cat-boneless', name: 'Boneless', slug: 'boneless' },
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 10,
    sortOrder: 20,
    optionGroups: [],
  },
  {
    id: 'item-chicken-popcorn',
    name: 'Chicken Popcorn',
    slug: 'chicken-popcorn',
    description: '10 Pieces of crunchy, bite-sized chicken popcorn bursting with savory spices. Served with Mayonnaise Dip.',
    price: 170,
    categoryId: 'cat-boneless',
    category: { id: 'cat-boneless', name: 'Boneless', slug: 'boneless' },
    imageUrl: 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 10,
    sortOrder: 21,
    optionGroups: [],
  },

  // 8. LOADED CHICKEN
  {
    id: 'item-chicken-loaded-fries',
    name: 'Chicken Loaded Fries',
    slug: 'chicken-loaded-fries',
    description: 'Crispy French fries generously topped with tender shredded chicken, melted cheese sauce, and special seasoning.',
    price: 190,
    categoryId: 'cat-loaded',
    category: { id: 'cat-loaded', name: 'Loaded Chicken', slug: 'loaded-chicken' },
    imageUrl: '/images/dishes/chicken-loaded-fries.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 12,
    sortOrder: 22,
    optionGroups: [],
  },
  {
    id: 'item-fish-loaded-fries',
    name: 'Fish Loaded Fries',
    slug: 'fish-loaded-fries',
    description: 'Golden crispy fries loaded with crispy fish bites, creamy tartar drizzle, and herbs.',
    price: 190,
    categoryId: 'cat-loaded',
    category: { id: 'cat-loaded', name: 'Loaded Chicken', slug: 'loaded-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1518013034458-30b0ee243591?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 12,
    sortOrder: 23,
    optionGroups: [],
  },
  {
    id: 'item-spl-loaded-chicken',
    name: 'Spl. Loaded Chicken',
    slug: 'spl-loaded-chicken',
    description: 'Chef special signature loaded feast with pressure-fried broasted chicken chunks, double cheese, and in-house sauce.',
    price: 220,
    categoryId: 'cat-loaded',
    category: { id: 'cat-loaded', name: 'Loaded Chicken', slug: 'loaded-chicken' },
    imageUrl: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=800&auto=format&fit=crop&q=85',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    preparationTimeMinutes: 15,
    sortOrder: 24,
    optionGroups: [],
  },

  // 9. ADD-ONS
  {
    id: 'item-garlic-dip',
    name: 'Garlic Dip',
    slug: 'garlic-dip',
    description: 'Authentic thick Lebanese garlic toum sauce, perfect with broasted chicken.',
    price: 20,
    categoryId: 'cat-addons',
    category: { id: 'cat-addons', name: 'Add-Ons', slug: 'add-ons' },
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 2,
    sortOrder: 25,
    optionGroups: [],
  },
  {
    id: 'item-bun',
    name: 'Bun',
    slug: 'bun',
    description: 'Freshly baked soft warm dinner bun.',
    price: 10,
    categoryId: 'cat-addons',
    category: { id: 'cat-addons', name: 'Add-Ons', slug: 'add-ons' },
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 2,
    sortOrder: 26,
    optionGroups: [],
  },
  {
    id: 'item-inhouse-sauce',
    name: 'Inhouse Sauce',
    slug: 'inhouse-sauce',
    description: 'Signature spicy and tangy in-house recipe sauce.',
    price: 30,
    categoryId: 'cat-addons',
    category: { id: 'cat-addons', name: 'Add-Ons', slug: 'add-ons' },
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 2,
    sortOrder: 27,
    optionGroups: [],
  },
  {
    id: 'item-piri-piri-sprinkler',
    name: 'Piri Piri Sprinkler (Powder)',
    slug: 'piri-piri-sprinkler-powder',
    description: 'Fiery in-house piri piri spice sprinkle blend for extra punch.',
    price: 50,
    categoryId: 'cat-addons',
    category: { id: 'cat-addons', name: 'Add-Ons', slug: 'add-ons' },
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=85',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    preparationTimeMinutes: 2,
    sortOrder: 28,
    optionGroups: [],
  },
];

export async function getMenuData() {
  try {
    const categories = await prisma.category.findMany({
      where: { isActive: true },
      orderBy: { sortOrder: 'asc' },
    });

    const items = await prisma.menuItem.findMany({
      include: {
        category: true,
        optionGroups: {
          include: {
            options: true,
          },
        },
      },
      orderBy: { sortOrder: 'asc' },
    });

    if (categories.length > 0 && items.length > 0) {
      return {
        categories: categories.map((c: any) => ({
          id: c.id,
          name: c.name,
          slug: c.slug,
          imageUrl: c.imageUrl,
        })),
        items: items as unknown as MenuItemWithDetails[],
      };
    }
  } catch (err) {
    console.warn('Database query fallback to official menu card dataset:', err);
  }

  return {
    categories: OFFICIAL_CATEGORIES,
    items: OFFICIAL_MENU_ITEMS,
  };
}
